kind: pipeline
name: default

clone:
  - depth: 1
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jarry6/cms
      tags: latest
      username: jarry6
      password:
          from_secret: docker_password
trigger:
  branch:
    - main
    - feature
