kind: pipeline
name: default

clone:
  depth: 1
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: uhub.service.ucloud.cn/fze/cms
      tags: latest
      registry: uhub.service.ucloud.cn
      username: 
          from_secret: docker_username
      password:
          from_secret: docker_password
trigger:
  branch:
    - main
    - feature
